sudo: required
services:
  - docker

  before_install:
    - docker build -t vondoste/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vondoste/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-us-east-2-637423311347"
    bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
